-- Your CREATE TABLE and INSERT statements go here
CREATE TABLE account (
    AccountID INT PRIMARY KEY,
    AccountNumber VARCHAR2(20) UNIQUE NOT NULL,
    CustomerID INT NOT NULL,
    Saldo NUMBER NOT NULL
);

CREATE TABLE transactions (
    TransactionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountNumber VARCHAR2(20),
    Amount NUMBER NOT NULL,
    TransactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AccountNumber) REFERENCES account(AccountNumber)
);

-- Insert sample data
INSERT INTO account (AccountID, AccountNumber, CustomerID, Saldo) VALUES
(1, 'AC001001', 1, 1000.00),
(2, 'AC001002', 1, 2500.50),
(3, 'AC002001', 2, 500.75);

INSERT INTO transactions (AccountNumber, Amount, TransactionDate) VALUES
('AC001001', 100.00, TIMESTAMP '2024-10-30 09:15:00'),
('AC001002', -50.25, TIMESTAMP '2024-10-30 10:30:00'),
('AC002001', 200.50, TIMESTAMP '2024-10-30 11:45:00');