CREATE TABLE account (
    AccountID INT PRIMARY KEY,
    AccountNumber VARCHAR2(20) UNIQUE NOT NULL,
    CustomerID INT NOT NULL,
    Saldo NUMBER NOT NULL
);

CREATE TABLE transactions (
    TransactionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountNumber VARCHAR2(20),
    Amount NUMBER NOT NULL,
    TransactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AccountNumber) REFERENCES account(AccountNumber)
);